version: "3.9"
services:
  db:
    container_name: ma-db
    image: postgres:15.2-alpine
    restart: unless-stopped
    networks:
      - db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  db-adminer:
    image: adminer
    restart: on-failure
    ports:
      - "18080:8080"
    networks:
      - db
networks:
  db:
volumes:
  db-data:
